### ISSUE TITLE
Enable web push notification fails

### ISSUE THREAD

**Issue by JarnDev** [magicbell-io/magicbell-js#129]
Enabling push notifications on IOS fails with the message 'Browser not supported

Iphone 13 Pro Max
IOS 16.5

https://github.com/magicbell-io/magicbell-js/assets/20113585/a9ba5e14-4641-42d0-baf8-e15cd20e5d63

**Comment by moxley01** [comment]
Hey @JarnDev . Our messaging could definitely be improved here, but typically a site needs to be 'installed' on iOS before it can utilise push notifications

Try going to the share menu -> Add To Home Screen -> Add

This adds an icon to your home screen. Click on it to launch, and _then_ try the steps you recorded.

Keen to hear if this works! If not, we can debug further. But its a good place to start.

**Comment by unamashana** [comment]
Related discussion - https://github.com/orgs/magicbell-io/discussions/110
